# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bgat/lge/radarhal/csvpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bgat/lge/radarhal/csvpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bgat/lge/radarhal/csvpp/CMakeFiles /home/bgat/lge/radarhal/csvpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bgat/lge/radarhal/csvpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csvpp

# Build rule for target.
csvpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csvpp
.PHONY : csvpp

# fast build rule for target.
csvpp/fast:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/build
.PHONY : csvpp/fast

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/writer.o: src/writer.cpp.o
.PHONY : src/writer.o

# target to build an object file
src/writer.cpp.o:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/writer.cpp.o
.PHONY : src/writer.cpp.o

src/writer.i: src/writer.cpp.i
.PHONY : src/writer.i

# target to preprocess a source file
src/writer.cpp.i:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/writer.cpp.i
.PHONY : src/writer.cpp.i

src/writer.s: src/writer.cpp.s
.PHONY : src/writer.s

# target to generate assembly for a file
src/writer.cpp.s:
	$(MAKE) -f CMakeFiles/csvpp.dir/build.make CMakeFiles/csvpp.dir/src/writer.cpp.s
.PHONY : src/writer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... csvpp"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/writer.o"
	@echo "... src/writer.i"
	@echo "... src/writer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

